### ISSUE TITLE
Fix proposal task with cron

### ISSUE THREAD

**Issue by pincopallino93** [PRIMETIME4U/PRIMETIME4U-server#60]
The proposal task with the cron at the 3 am does not work. Probably it is caused by the proposal api call that suggest movie of today and not movie of tomorrow

**Comment by Ionita** [comment]
Add app notification which advise user that are not available movie suggestions for tomorrow and tell to him when will be available new suggestions.

**Comment by JohnnyConan** [comment]
Fixed, adding cron retrieval at 7.00 am
