### ISSUE TITLE
Some movie info are wrong

### ISSUE THREAD

**Issue by pincopallino93** [PRIMETIME4U/PRIMETIME4U-server#61]
E.g: Io e Marley, Una famiglia all'improvviso

**Comment by Ionita** [comment]
Sometime we have problems with movie year and the search take another movie, searched just with the name.

**Comment by Ionita** [comment]
Make a compare between director of a movie taked from filmtv with director of the same movie retrieved on IMDB. If directors are different then the movie is wrong, so we should save just filmtv informations and save it on our database.
